### ISSUE TITLE
Fix installation to paths with spaces

### ISSUE THREAD

**Issue by unflxw** [appsignal/appsignal-nodejs#907] opened 2023-07-04 09:37 UTC
When the full file system path of the folder where the `package.json` is located contains spaces, the AppSignal extension fails to compile when installing the AppSignal package from npm. At least on macOS, but probably not just on macOS. Repro:

```
mkdir "foo bar"
cd "foo bar"
npm init -y
npm i --save @appsignal/nodejs@latest
cat node_modules/@appsignal/nodejs/ext/install.report
```

You'll see in the install report that `node-gyp` at some point passes a path to `clang` unquoted, resulting in:
```
clang: error: no such file or directory: 'bar/node_modules/node-addon-api'
```

It's unclear at this moment whether this is an issue with node-gyp itself, or with how we configure it.

It looks to be a bug in node-gyp: https://github.com/appsignal/appsignal-nodejs/issues/907#issuecomment-1680465946

**Comment by tombruijn** [comment] 2023-07-05 07:27
This is the config we set: https://github.com/appsignal/appsignal-nodejs/blob/main/binding.gyp
Maybe something needs another set of quotes to escape it.

**Comment by tombruijn** [comment] 2023-08-16 11:54
I can't find any place we set the current path and don't escape it.

This issue (https://github.com/nodejs/node-gyp/issues/65), although closed, has activity on it indicating it's not fixed in the latest versions. Here's a possible fix in a PR: https://github.com/nodejs/node-gyp/pull/2556

If it exists in node-gyp and it's not being fixed we can tell people to not use spaces in their path or switch to another tool.

**Comment by tombruijn** [comment] 2023-08-16 14:32
I've confirmed the issue is fixed by using https://github.com/nodejs/node-gyp/pull/2556, so it's not on our end. What shall we do: document, make noise on the issues/PRs, switch to another tool?

**Comment by tombruijn** [comment] 2023-08-17 08:15
> Perhaps because of the comment that says that it should be fixed upstream, [where it hasn't been fixed either](https://github.com/nodejs/gyp-next/blob/d2dfe4e66b64c16b38bef984782db93d12674f05/pylib/gyp/generator/make.py#L1421).

I'd love it if we could move it along by providing a test case or fixing it upstream, if that's their preferred solution.

I won't say I understand the code fully, but maybe passing a helper function like `EscapeShellArgument` as the `quoter` for https://github.com/nodejs/gyp-next/blob/d2dfe4e66b64c16b38bef984782db93d12674f05/pylib/gyp/generator/make.py#L1421 could be the fix.

```diff
-            self.WriteList(includes, "INCS_%s" % configname, prefix="-I")
+            self.WriteList(includes, "INCS_%s" % configname, prefix="-I", quoter=EscapeShellArgument)
```

The more difficult part (for me) will be a sending a PR with a reproducible test case.

> I don't know what alternatives exist to node-gyp, either. Perhaps if the ecosystem at large tacitly accepts that their tooling is broken, we should too.

cmake-js #386 got suggested once, would also remove our Python dependency(?)

**Comment by tombruijn** [comment] 2023-08-17 08:49
Submitted the fix upstream (the work of @davej (oh hi 👋)) in https://github.com/nodejs/gyp-next/pull/204. Let's see what happens.

**Comment by tombruijn** [comment] 2024-04-29 07:42
Fix submitted upstream in https://github.com/nodejs/gyp-next/pull/204. Closing issue, although I don't see it being merged soon.

**Closed by tombruijn** 2024-04-29 07:42 UTC
Labels: bug
