### ISSUE TITLE
Next.js non-root paths are reported as `GET [unknown route]`

### ISSUE THREAD

**Issue by jeffkreeftmeijer** [appsignal/appsignal-nodejs#381] opened 2021-04-16 13:50 UTC
From our testing in #380, @shairyar found that non-root paths aren’t recognized correctly in Next.js applications. I’ve written a [failing test case](https://appsignal.semaphoreci.com/workflows/7f6b3663-d31a-436d-a738-f67eae0b8009?pipeline_id=1e483508-df7e-42c5-bae5-49d072c4e22a) in the [nextjs-non-root-paths](https://github.com/appsignal/appsignal-nodejs/tree/nextjs-non-root-paths) branch. I haven’t yet found a fix to it yet.

**Comment by tombruijn** [comment] 2021-04-19 08:21
Looks like a duplicate of #337

**Comment by shairyar** [comment] 2021-04-19 09:08
https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/4356044/conversations/16410700030073

**Closed** 2021-04-19 11:16 UTC
Labels: bug
