### ISSUE TITLE
Remove integration side sendParams and sendSessionData checks

### ISSUE THREAD

**Issue by tombruijn** [appsignal/appsignal-nodejs#751] opened 2022-10-07 08:59 UTC
Noemi brought up in https://github.com/appsignal/appsignal-agent/pull/824#issuecomment-1270214591 that we no longer need to do the if-statements for `sendParams` and `sendSessionData` in the [client](https://github.com/appsignal/appsignal-nodejs/blob/opentelemetry/src/client.ts#L218-L244).

The sendParams and sendSessionData is checked in the extension since PR https://github.com/appsignal/appsignal-agent/pull/824 and the [related Node.js PR](https://github.com/appsignal/appsignal-nodejs/pull/747).

## To do

- [ ] Remove if-statements checking for `sendParams` and `sendSessionData` in the Node.js package.

**Comment by luismiramirez** [comment] 2022-10-10 12:23
> How it's currently implemented, the if-statements reduce the overhead of creating the params and session data objects, converting them to a JSON string, converting that into Data struct and sending it to extension.

This is the caveat I wanted to find in the back of my head in today's call.

I think keeping them and closing the issue is the best idea.

**Closed** 2022-10-10 12:27 UTC
Labels: chore
