### ISSUE TITLE
Express not instrumented when using own HTTP server

### ISSUE THREAD

**Issue by luismiramirez** [appsignal/appsignal-nodejs#832] opened 2023-01-12 14:10 UTC
The Express instrumentation does not work if the app server is initialized using the http/https Node.js modules as in:

```js
var express = require('express');
var http = require('http');

var app = express();
var server = http.createServer(app);

server.listen(1234);
```

When starting the app like this, the request root span is an HTTP one with a generic name that misses all the info set up by the Express instrumentation.

## To do

- [ ] Timebox 1 day - research if it's not an issue on our end, if not;
- [ ] Report the issue on OpenTelemetry upstream

**Comment by luismiramirez** [comment] 2023-01-12 14:11
Related conversation: https://app.intercom.com/a/apps/yzor8gyw/inbox/inbox/5138541/conversations/16410700168101

**Comment by unflxw** [comment] 2023-02-09 08:28
Can't reproduce. In my local tests, running an Express application with the Node.js HTTP server using `http.createServer(app)` results in both Express and HTTP spans appearing, and the instrumentation behaves as expected.

I have found [this closed issue describing a similar problem in the OpenTelemetry repo](https://github.com/open-telemetry/opentelemetry-js-contrib/issues/1166). [The solution to their issue](https://github.com/ringerc/otel-express-node-instrumentation-issue/commit/5016047eb9ca0da61186766ea671a12299394542) was to use `--external` in their `esbuild` build, which was also this user's setup.

As such, I believe this issue is fixed by @luismiramirez's [esbuild documentation PR](https://github.com/appsignal/appsignal-docs/pull/1077).

Closing.

**Closed by unflxw** 2023-02-09 08:28 UTC
Labels: bug, support
